#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
#更新软件列表
opkg update
#安装smartdns
opkg install luci-app-smartdns
opkg install luci-i18n-smartdns-zh-cn
#安装ssr-plus
opkg install luci-app-passwall
opkg install luci-i18n-passwall-zh-cn
#安装openssh-sftp-server
opkg install openssh-sftp-server
